import type { Metadata } from 'next';
import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthContextProvider } from '@/context/authUserContext';
import { SocketContextProvider } from '@/context/socketContext';
import { ChatUsersContextProvider } from '@/context/chatUsersContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Social App',
    description: 'Generated by Social app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning>
                <AuthContextProvider>
                    <SocketContextProvider>
                        <ChatUsersContextProvider>{children}</ChatUsersContextProvider>
                    </SocketContextProvider>
                </AuthContextProvider>
            </body>
        </html>
    );
};

export default RootLayout;
